runtime: nodejs20

# Comando que o App Engine deve rodar ao subir a sua app:
entrypoint: node dist/main.js

# (Opcional) Variáveis de ambiente
env_variables:
  NODE_ENV: 'production'
  LOG_BITRIX_LIB: false
  PORT: 8080
  GOOGLE_CLOUD_PROJECT:
  BITRIX_WEBHOOK_URL:
  BITRIX_WEBHOOK_USER_ID:
automatic_scaling:
  max_instances: 1
